### ISSUE TITLE
Criar componente de publicação

### ISSUE THREAD

**Issue by valn1** [valn1/ixc-bluedit#3]
deverá ser criado um componente para as publicações individuais.
![image](https://github.com/valn1/ixc-bluedit/assets/40465512/69a12911-84f6-46d7-97b5-e7cfba7e42bd)
o componente deverá ter os seguintes parâmetros:
userMail, userName, title.
esse componente deve receber como children a postagem em si, seja uma foto, album ou texto

na parte de baixo, deverá existir um botão para abrir os comentários(por enquanto, não precisa fazer nada)

**Comment by valn1** [comment]
a imagem do usuário deverá ser um link para a api do gravatar
como essa:
https://www.gravatar.com/avatar/d4c74594d841139328695756648b6bd6
note que a url usa um hash, esse hash deve ser criado a partir do email de usuário do post

**Comment by AlexandreBeilner** [comment]
Nunca tinha feito essa parte de hash, então fiquei um pouco preso nisso, no final deu certo, não tenho certeza se era pra ser feito dessa forma.
